more robust run script

diff --git a/run b/run
--- a/run
+++ b/run
@@ -5,38 +5,33 @@
 # Or, run with a parameter service name (from docker-compose) to restart just that service
 # `./run meminator`
 
-docker compose up --build -d $*
+if ! docker compose up --build -d "$@"; then
+  echo ""
+  echo "Failed to build or start services!"
+  exit 1
+fi
 
 # Check if running in GitHub Codespaces
 if [ -n "$CODESPACES" ]; then
-    echo "Running in GitHub Codespaces."
+  echo "Running in GitHub Codespaces."
 
-    # Get Codespaces name and port
-    CODESPACE_NAME=$(echo $CODESPACE_NAME)
-    APP_PORT=10114
+  APP_PORT=10114
 
-    URL="https://${CODESPACE_NAME}-${APP_PORT}.app.github.dev"
-
-    echo "Meminator running on port 10114 at: $URL"
-
-    exit 0
-fi
+  URL="https://${CODESPACE_NAME}-${APP_PORT}.app.github.dev"
 
 # Check if running in Gitpod
-if [ -n "$GITPOD_INSTANCE_ID" ]; then
-    echo "Running in Gitpod."
+elif [ -n "$GITPOD_INSTANCE_ID" ]; then
+  echo "Running in Gitpod."
 
-    # Get the workspace url
-    URL=$(gp url 10114)
+  # Get the workspace url
+  URL=$(gp url 10114)
 
-    echo "Meminator running on port 10114 at: $URL"
+else
+  # Default to local environment
+  echo "Running locally."
 
-    exit 0
+  URL="http://localhost:10114/"
+
 fi
-
-# Default to local environment
-echo "Running locally."
-
-URL="http://localhost:10114/" 
 
 echo "Meminator running on port 10114 at: $URL"
